/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AskCoachRouteImport } from './routes/ask-coach'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as MonitorRouteImport } from './routes/monitor'
import { Route as PlayersRouteImport } from './routes/players'
import { Route as PostMatchRouteImport } from './routes/post-match'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as PreMatchRouteImport } from './routes/pre-match'
import { Route as ScoutingRouteImport } from './routes/scouting'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TeamRouteImport } from './routes/team'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AskCoachRoute = AskCoachRouteImport.update({
  id: '/ask-coach',
  path: '/ask-coach',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitorRoute = MonitorRouteImport.update({
  id: '/monitor',
  path: '/monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersRoute = PlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => rootRouteImport,
} as any)
const PostMatchRoute = PostMatchRouteImport.update({
  id: '/post-match',
  path: '/post-match',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const PreMatchRoute = PreMatchRouteImport.update({
  id: '/pre-match',
  path: '/pre-match',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoutingRoute = ScoutingRouteImport.update({
  id: '/scouting',
  path: '/scouting',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ask-coach': typeof AskCoachRoute
  '/knowledge': typeof KnowledgeRoute
  '/monitor': typeof MonitorRoute
  '/players': typeof PlayersRoute
  '/post-match': typeof PostMatchRoute
  '/practice': typeof PracticeRoute
  '/pre-match': typeof PreMatchRoute
  '/scouting': typeof ScoutingRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ask-coach': typeof AskCoachRoute
  '/knowledge': typeof KnowledgeRoute
  '/monitor': typeof MonitorRoute
  '/players': typeof PlayersRoute
  '/post-match': typeof PostMatchRoute
  '/practice': typeof PracticeRoute
  '/pre-match': typeof PreMatchRoute
  '/scouting': typeof ScoutingRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ask-coach': typeof AskCoachRoute
  '/knowledge': typeof KnowledgeRoute
  '/monitor': typeof MonitorRoute
  '/players': typeof PlayersRoute
  '/post-match': typeof PostMatchRoute
  '/practice': typeof PracticeRoute
  '/pre-match': typeof PreMatchRoute
  '/scouting': typeof ScoutingRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ask-coach'
    | '/knowledge'
    | '/monitor'
    | '/players'
    | '/post-match'
    | '/practice'
    | '/pre-match'
    | '/scouting'
    | '/settings'
    | '/team'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ask-coach'
    | '/knowledge'
    | '/monitor'
    | '/players'
    | '/post-match'
    | '/practice'
    | '/pre-match'
    | '/scouting'
    | '/settings'
    | '/team'
  id:
    | '__root__'
    | '/'
    | '/ask-coach'
    | '/knowledge'
    | '/monitor'
    | '/players'
    | '/post-match'
    | '/practice'
    | '/pre-match'
    | '/scouting'
    | '/settings'
    | '/team'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AskCoachRoute: typeof AskCoachRoute
  KnowledgeRoute: typeof KnowledgeRoute
  MonitorRoute: typeof MonitorRoute
  PlayersRoute: typeof PlayersRoute
  PostMatchRoute: typeof PostMatchRoute
  PracticeRoute: typeof PracticeRoute
  PreMatchRoute: typeof PreMatchRoute
  ScoutingRoute: typeof ScoutingRoute
  SettingsRoute: typeof SettingsRoute
  TeamRoute: typeof TeamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask-coach': {
      id: '/ask-coach'
      path: '/ask-coach'
      fullPath: '/ask-coach'
      preLoaderRoute: typeof AskCoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitor': {
      id: '/monitor'
      path: '/monitor'
      fullPath: '/monitor'
      preLoaderRoute: typeof MonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players': {
      id: '/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof PlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-match': {
      id: '/post-match'
      path: '/post-match'
      fullPath: '/post-match'
      preLoaderRoute: typeof PostMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pre-match': {
      id: '/pre-match'
      path: '/pre-match'
      fullPath: '/pre-match'
      preLoaderRoute: typeof PreMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scouting': {
      id: '/scouting'
      path: '/scouting'
      fullPath: '/scouting'
      preLoaderRoute: typeof ScoutingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AskCoachRoute: AskCoachRoute,
  KnowledgeRoute: KnowledgeRoute,
  MonitorRoute: MonitorRoute,
  PlayersRoute: PlayersRoute,
  PostMatchRoute: PostMatchRoute,
  PracticeRoute: PracticeRoute,
  PreMatchRoute: PreMatchRoute,
  ScoutingRoute: ScoutingRoute,
  SettingsRoute: SettingsRoute,
  TeamRoute: TeamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
