import { ChevronDown, Download, UserRound } from "lucide-react";
import { Button } from "@/components/ui/button";
import { ComparisonBar, MetricCard, PageIntro, Panel, SectionHeading } from "@/components/xamcoach/core";
import { MiniTrend, ShotChart } from "@/components/xamcoach/visuals";
const zones=[['At rim','63.8%','26%','1.28'],['Paint','48.2%','18%','0.96'],['Mid-range','41.4%','15%','0.83'],['3PT','36.7%','41%','1.10']];
export function PlayerPage(){return <><PageIntro title="Player Analysis" description="Season profile, shooting tendencies and creation context." actions={<><Button variant="outline"><Download/>Export</Button><Button variant="outline">2025–26<ChevronDown/></Button></>}/>
<Panel className="mb-6 overflow-hidden"><div className="flex flex-col gap-5 p-5 sm:flex-row sm:items-center"><span className="grid size-20 shrink-0 place-items-center rounded-xl bg-secondary text-muted-foreground"><UserRound className="size-9"/></span><div className="flex-1"><p className="text-[10px] font-bold uppercase tracking-[0.12em] text-data">Guard · Lyon ASVEL</p><h2 className="mt-1 text-2xl font-bold">Marine Johannès</h2><p className="mt-1 text-xs text-muted-foreground">#23 · 174 cm · 31 years</p></div><div className="grid grid-cols-3 gap-6 border-t border-border pt-4 sm:border-l sm:border-t-0 sm:pl-6 sm:pt-0">{[['PPG','14.8'],['AST','4.2'],['REB','3.8']].map(([l,v])=><div key={l}><p className="text-[10px] font-bold text-muted-foreground">{l}</p><p className="mt-1 text-2xl font-bold tabular-nums">{v}</p></div>)}</div></div></Panel>
<div className="grid gap-6 xl:grid-cols-[1.1fr_.9fr]"><div className="space-y-6"><div><SectionHeading title="Performance" description="Verified season statistics · 11 games"/><div className="grid overflow-hidden rounded-xl border border-border sm:grid-cols-2 lg:grid-cols-4"><MetricCard label="FG%" value="48.1%" detail="82nd percentile" trend="up"/><MetricCard label="3P%" value="36.7%" detail="71st percentile"/><MetricCard label="Usage" value="24.6%" detail="Team: 2nd"/><MetricCard label="AST / TOV" value="2.3" detail="League: 1.7" trend="up"/></div></div><Panel className="p-5"><SectionHeading title="Recent form" description="Game score · last 9 appearances"/><MiniTrend/><div className="mt-1 flex justify-between text-[10px] text-muted-foreground"><span>vs BLMA</span><span>vs BOUR</span><span>vs TMB</span></div></Panel><Panel className="p-5"><SectionHeading title="Creation profile" description="Share of made field goals"/><div className="grid gap-6 sm:grid-cols-2"><ComparisonBar label="Assisted" value={41} average={53} unit="%"/><ComparisonBar label="Unassisted" value={59} average={47} unit="%"/></div></Panel></div>
<div><SectionHeading title="Shot profile" description="All attempts · regular season"/><Panel className="p-4"><ShotChart/><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[420px] text-left text-xs"><thead><tr className="border-b border-border text-[10px] uppercase text-muted-foreground"><th className="pb-2 font-semibold">Zone</th><th className="pb-2 text-right font-semibold">FG%</th><th className="pb-2 text-right font-semibold">Frequency</th><th className="pb-2 text-right font-semibold">Pts / shot</th></tr></thead><tbody>{zones.map(z=><tr key={z[0]} className="border-b border-border last:border-0"><td className="py-3 font-semibold">{z[0]}</td>{z.slice(1).map(x=><td key={x} className="py-3 text-right font-medium tabular-nums">{x}</td>)}</tr>)}</tbody></table></div></Panel></div></div></>}
